package event

// Code generated by tools/codegen/event. DO NOT EDIT.

import (
	"reflect"

	"github.com/diamondburned/arikawa/v3/discord"
	"github.com/diamondburned/arikawa/v3/gateway"
)

var eventIntents = map[reflect.Type]gateway.Intents{
	reflect.TypeOf(new(WebhooksUpdate)):             32,
	reflect.TypeOf(new(ChannelDelete)):              1,
	reflect.TypeOf(new(GuildIntegrationsUpdate)):    16,
	reflect.TypeOf(new(GuildRoleCreate)):            1,
	reflect.TypeOf(new(GuildRoleUpdate)):            1,
	reflect.TypeOf(new(MessageUpdate)):              4608,
	reflect.TypeOf(new(PresenceUpdate)):             256,
	reflect.TypeOf(new(VoiceStateUpdate)):           128,
	reflect.TypeOf(new(RelationshipAdd)):            0,
	reflect.TypeOf(new(Hello)):                      0,
	reflect.TypeOf(new(GuildCreate)):                1,
	reflect.TypeOf(new(GuildUpdate)):                1,
	reflect.TypeOf(new(GuildMemberListUpdate)):      0,
	reflect.TypeOf(new(InviteCreate)):               64,
	reflect.TypeOf(new(VoiceServerUpdate)):          0,
	reflect.TypeOf(new(RelationshipRemove)):         0,
	reflect.TypeOf(new(Resumed)):                    0,
	reflect.TypeOf(new(ChannelPinsUpdate)):          4097,
	reflect.TypeOf(new(GuildBanRemove)):             4,
	reflect.TypeOf(new(ChannelUpdate)):              1,
	reflect.TypeOf(new(GuildDelete)):                1,
	reflect.TypeOf(new(GuildMembersChunk)):          0,
	reflect.TypeOf(new(UserSettingsUpdate)):         0,
	reflect.TypeOf(new(ChannelCreate)):              1,
	reflect.TypeOf(new(ChannelUnreadUpdate)):        0,
	reflect.TypeOf(new(GuildEmojisUpdate)):          8,
	reflect.TypeOf(new(GuildRoleDelete)):            1,
	reflect.TypeOf(new(MessageReactionRemoveAll)):   9216,
	reflect.TypeOf(new(SessionsReplace)):            0,
	reflect.TypeOf(new(TypingStart)):                18432,
	reflect.TypeOf(new(UserUpdate)):                 0,
	reflect.TypeOf(new(InvalidSession)):             0,
	reflect.TypeOf(new(GuildBanAdd)):                4,
	reflect.TypeOf(new(GuildMemberAdd)):             2,
	reflect.TypeOf(new(MessageCreate)):              4608,
	reflect.TypeOf(new(MessageReactionAdd)):         9216,
	reflect.TypeOf(new(MessageReactionRemove)):      9216,
	reflect.TypeOf(new(InteractionCreate)):          0,
	reflect.TypeOf(new(UserGuildSettingsUpdate)):    0,
	reflect.TypeOf(new(Ready)):                      0,
	reflect.TypeOf(new(GuildMemberRemove)):          2,
	reflect.TypeOf(new(InviteDelete)):               64,
	reflect.TypeOf(new(MessageDelete)):              4608,
	reflect.TypeOf(new(MessageDeleteBulk)):          512,
	reflect.TypeOf(new(MessageReactionRemoveEmoji)): 9216,
	reflect.TypeOf(new(PresencesReplace)):           0,
	reflect.TypeOf(new(ApplicationCommandUpdate)):   0,
	reflect.TypeOf(new(ReadySupplemental)):          0,
	reflect.TypeOf(new(GuildMemberUpdate)):          2,
	reflect.TypeOf(new(MessageAck)):                 0,
	reflect.TypeOf(new(UserNoteUpdate)):             0,
}

type (
	WebhooksUpdate struct {
		*Base
		*gateway.WebhooksUpdateEvent
	}
	ChannelDelete struct {
		*Base
		*gateway.ChannelDeleteEvent

		Old *discord.Channel
	}
	GuildIntegrationsUpdate struct {
		*Base
		*gateway.GuildIntegrationsUpdateEvent
	}
	GuildRoleCreate struct {
		*Base
		*gateway.GuildRoleCreateEvent
	}
	GuildRoleUpdate struct {
		*Base
		*gateway.GuildRoleUpdateEvent

		Old *discord.Role
	}
	MessageUpdate struct {
		*Base
		*gateway.MessageUpdateEvent

		Old *discord.Message
	}
	PresenceUpdate struct {
		*Base
		*gateway.PresenceUpdateEvent

		Old *discord.Presence
	}
	VoiceStateUpdate struct {
		*Base
		*gateway.VoiceStateUpdateEvent
	}
	RelationshipAdd struct {
		*Base
		*gateway.RelationshipAddEvent
	}
	Hello struct {
		*Base
		*gateway.HelloEvent
	}
	GuildCreate struct {
		*Base
		*gateway.GuildCreateEvent
	}
	GuildUpdate struct {
		*Base
		*gateway.GuildUpdateEvent

		Old *discord.Guild
	}
	GuildMemberListUpdate struct {
		*Base
		*gateway.GuildMemberListUpdate
	}
	InviteCreate struct {
		*Base
		*gateway.InviteCreateEvent
	}
	VoiceServerUpdate struct {
		*Base
		*gateway.VoiceServerUpdateEvent
	}
	RelationshipRemove struct {
		*Base
		*gateway.RelationshipRemoveEvent
	}
	Resumed struct {
		*Base
		*gateway.ResumedEvent
	}
	ChannelPinsUpdate struct {
		*Base
		*gateway.ChannelPinsUpdateEvent
	}
	GuildBanRemove struct {
		*Base
		*gateway.GuildBanRemoveEvent
	}
	ChannelUpdate struct {
		*Base
		*gateway.ChannelUpdateEvent

		Old *discord.Channel
	}
	GuildDelete struct {
		*Base
		*gateway.GuildDeleteEvent

		Old *discord.Guild
	}
	GuildMembersChunk struct {
		*Base
		*gateway.GuildMembersChunkEvent
	}
	UserSettingsUpdate struct {
		*Base
		*gateway.UserSettingsUpdateEvent
	}
	ChannelCreate struct {
		*Base
		*gateway.ChannelCreateEvent
	}
	ChannelUnreadUpdate struct {
		*Base
		*gateway.ChannelUnreadUpdateEvent
	}
	GuildEmojisUpdate struct {
		*Base
		*gateway.GuildEmojisUpdateEvent
	}
	GuildRoleDelete struct {
		*Base
		*gateway.GuildRoleDeleteEvent

		Old *discord.Role
	}
	MessageReactionRemoveAll struct {
		*Base
		*gateway.MessageReactionRemoveAllEvent
	}
	SessionsReplace struct {
		*Base
		*gateway.SessionsReplaceEvent
	}
	TypingStart struct {
		*Base
		*gateway.TypingStartEvent
	}
	UserUpdate struct {
		*Base
		*gateway.UserUpdateEvent
	}
	InvalidSession struct {
		*Base
		*gateway.InvalidSessionEvent
	}
	GuildBanAdd struct {
		*Base
		*gateway.GuildBanAddEvent
	}
	GuildMemberAdd struct {
		*Base
		*gateway.GuildMemberAddEvent
	}
	MessageCreate struct {
		*Base
		*gateway.MessageCreateEvent
	}
	MessageReactionAdd struct {
		*Base
		*gateway.MessageReactionAddEvent
	}
	MessageReactionRemove struct {
		*Base
		*gateway.MessageReactionRemoveEvent
	}
	InteractionCreate struct {
		*Base
		*gateway.InteractionCreateEvent
	}
	UserGuildSettingsUpdate struct {
		*Base
		*gateway.UserGuildSettingsUpdateEvent
	}
	Ready struct {
		*Base
		*gateway.ReadyEvent
	}
	GuildMemberRemove struct {
		*Base
		*gateway.GuildMemberRemoveEvent

		Old *discord.Member
	}
	InviteDelete struct {
		*Base
		*gateway.InviteDeleteEvent
	}
	MessageDelete struct {
		*Base
		*gateway.MessageDeleteEvent

		Old *discord.Message
	}
	MessageDeleteBulk struct {
		*Base
		*gateway.MessageDeleteBulkEvent
	}
	MessageReactionRemoveEmoji struct {
		*Base
		*gateway.MessageReactionRemoveEmojiEvent
	}
	PresencesReplace struct {
		*Base
		*gateway.PresencesReplaceEvent
	}
	ApplicationCommandUpdate struct {
		*Base
		*gateway.ApplicationCommandUpdateEvent
	}
	ReadySupplemental struct {
		*Base
		*gateway.ReadySupplementalEvent
	}
	GuildMemberUpdate struct {
		*Base
		*gateway.GuildMemberUpdateEvent

		Old *discord.Member
	}
	MessageAck struct {
		*Base
		*gateway.MessageAckEvent
	}
	UserNoteUpdate struct {
		*Base
		*gateway.UserNoteUpdateEvent
	}
)
