name: Lint

on: [pull_request]

jobs:
  review:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
        with:
          path: ./go/src/github.com/${{ github.repository }}
      - name: Change Directory to v2
        run: cd v2/
      - name: Lint Project
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-review
